substitutions:
  log_baud_rate: '9600'
  upper_devicename: CCU6225 Hack
  devicename: ccu6225-hacker-1
  wifi_ip: !secret ip_ccu6225-hacker-1
  location: "Мест установки"
  hardware: "ESP32"
  ccu6225_gsm_number: !secret CCU6225_master_number
  ccu6225_password: !secret CCU6225_pass

packages:
  device_base: !include __device_base_mini.yaml

esphome:
  name: $devicename
  project:
    name: "CCU6225.Hacker"
    version: "ESP32"
  comment: "CCU6225 SIM300 hacker"
  includes:
    - my_components/CCU6225Hack/pdulib.h
    - my_components/CCU6225Hack/ccu6225hack.h
  on_boot :
    then:
      - lambda: |-
           // КОНФГУРИРОВАНИЕ
           // начало конфгурирования установка, подключение сенсоров, отправителя внутренних СМС, пароля, при необходимости лексемы баланса 
           //ccu6225setupStart("+74952457932" , "/1234" ,"BALANS"); 
           ccu6225setupStart("${ccu6225_gsm_number}" , "${ccu6225_password}" ,"BALANS"); 
           setRTC(time_id);
           addBinarySensor(kotel_, "KOTEL");
           // реле и выходы - переключатели
           addSwitch(kotelonoff_, "KOTEL");
           addSwitch(nagrev_, "NAGREV");
           addSwitch(dejNagr_, "DejNagr");
           addSwitch(sirena_, "SIRENA");
           // текстовые сенсоры
           setSecur(secur); // пояснение кто установил на охрану
           setInCont(inCont); // содержимое входящего смс
           setOutCont(outCont); // содержимое исходящих смс 
           setOutAddr(outAddr); // номер получателя 
           setInAddr(inAddr); // номер отправителя
           setTstamp(tstamp); // время сигналки
           setUnkrep(unkrep); // не распознанная команда в пртоколе обмена
           setGsmError(gsmError); // номер ошибки GSM обмена
           setTtime(ttimestr); // сенсор строки конфигураии TTIME
           // сенсоры
           setgsmRssi(gsmRssi); 
           setgsmQual(gsmQual);
           // бинарные сенсоры
           setOutsmsready(outsmsready_); // сенсор "готов принять смс для отправки"
           setSenreg(senreg); // статус регистраии в сети
           // переключатели           
           setOutsms(outsms_); // разрешение отправки смс наружу
           setInterch(interch_); // разрешение опроса проессора
           // аналоговые сенсоры, при необходимости их сенсоры аварии
           addSensor(septik_, "SEPTIK", septikAl_);
           addSensor(teplonos_, "TEPLONOS", teplonosAl_);
           addSensor(skvajina_, "SKVAJINA", skvajinaAl_);
           addSensor(inside_, "INSIDE", insideAl_);
           // бинарные сенсоры
           addBinarySensor(dver_, "DVER");
           addBinarySensor(dvij_, "DVIJENIE");
           addBinarySensor(dym_, "DYM");
           // логические лексемы
           addBoolLexema("AVARIA",true);
           addBoolLexema("NORMA",false);
           addBoolLexema("OTKRYTA",true);
           addBoolLexema("OBNARUJ.",true);
           // завершение конфигурирования
           ccu6225setupEnd();
           id(wdPin).turn_on(); // ДЛЯ АППАРАТНГО ВАЧДОГА
  on_loop:
    then:
      - lambda: |-
         // ДЛЯ АППАРАТНГО ВАЧДОГА
         id(wdPin).turn_off();
         delay(1);
         id(wdPin).turn_on();
         ccu6225loop();
esp32:
  board: esp32dev #nodemcu-32s
  framework:
     type: esp-idf
api:
  actions:
    - action: send_sms
      variables:
        recipient: string
        message: string
      then:
        - lambda: |-
            putNewSMS(message,recipient);
uart:
  - id: uart_tx
    tx_pin: GPIO21 # -> RXD (9)
    rx_pin: GPIO5  # <- R98 (10)
    baud_rate: 9600

  - id: uart_rx
    tx_pin: GPIO17 # -> R90 (7)
    rx_pin: GPIO16 # <-TXD (8)
    baud_rate: 9600

output:
  - id: wdPin
    platform: gpio
    pin: 
      number: GPIO4

text_sensor:
#кто поставил на охрану
  - platform: template
    name: ARM operator
    id: secur
#текст входящего сообщения
  - platform: template
    name: SMS Inbound
    id: inCont
#текст исходящего сообщения
  - platform: template
    name: SMS Outbound
    id: outCont
#получатель сообщения
  - platform: template
    name: SMS Recipient
    id: outAddr
#отправитель сообщения
  - platform: template
    name: SMS Sender
    id: inAddr
#Дата время GSM
  - platform: template
    name: GSM TimeStamp
    id: tstamp
#неизвестные данные
  - platform: template
    entity_category: diagnostic 
    name: GSM Unknown
    id: unkrep
#кто поставил на охрану
  - platform: template
    name: TTIME String
    id: ttimestr

number:
  - platform: template
    name: TTIME day
    id: ttday
    mode: box
    optimistic: true
    min_value: 1
    max_value: 5
    step: 1
  - platform: template
    name: TTIME hours
    id: tthour
    mode: box
    optimistic: true
    min_value: 0
    max_value: 23
    step: 1
  - platform: template
    name: TTIME minutes
    id: ttmin
    mode: box
    optimistic: true
    min_value: 0
    max_value: 59
    step: 1

button:
  - platform: template
    name: TTIME remove
    on_press:
      - lambda: |-
          delTtime();
  - platform: template
    name: TTIME add
    on_press:
      - lambda: |-
          addTtime(id(ttday).state,id(tthour).state,id(ttmin).state);
  - platform: template
    name: "Sync Time"
    on_press:
      - lambda: |-
           needTimeSync=true;
time:
  - platform: sntp
    id: time_id

sensor:
#GSM ERRR
  - platform: template
    entity_category: diagnostic 
    name: GSM ERROR
    id: gsmError
    accuracy_decimals: 0
#RSSI
  - platform: template
    entity_category: diagnostic 
    name: GSM RSSI
    id: gsmRssi
    unit_of_measurement: dB
    accuracy_decimals: 0
#возможные потери
  - platform: template
    entity_category: diagnostic 
    name: GSM Loss
    id: gsmQual
    unit_of_measurement: '%'
    accuracy_decimals: 1
# температура внутри
  - platform: template
    name: Inside
    id: inside_
    unit_of_measurement: °С  
    accuracy_decimals: 1     
# температура в септике
  - platform: template
    name: Septik
    id: septik_
    unit_of_measurement: °С  
    accuracy_decimals: 1     
# температура в кессоне
  - platform: template
    name: Caisson
    id: skvajina_
    unit_of_measurement: °С  
    accuracy_decimals: 1     
# температура теплоносителя
  - platform: template
    name: Coolant
    id: teplonos_
    unit_of_measurement: °С  
    accuracy_decimals: 1     
# заряд батареи
  - platform: template
    name: Battery
    id: battery_
    unit_of_measurement: '%'  
    accuracy_decimals: 0     
# баланс
  - platform: template
    name: Balance
    id: balans_
    unit_of_measurement: Руб.  
    accuracy_decimals: 2     

binary_sensor:
# диагностика результат поостановки сообщения в очередь
  - platform: template
    entity_category: diagnostic 
    device_class: problem
    name: Out SMS Ready
    id: outsmsready_
    filters: 
      - invert
# температура внутри ALARM
  - platform: template
    device_class: cold
    name: Inside °t
    id: insideAl_
# температура в септике ALARM
  - platform: template
    device_class: cold
    name: Septik °t
    id: septikAl_
# температура в кессоне ALARM
  - platform: template
    device_class: cold
    name: Caisson °t
    id: skvajinaAl_
# температура теплоносителя ALARM
  - platform: template
    device_class: heat
    name: Coolant °t
    id: teplonosAl_
#флаг регистрации в сети GSM
  - platform: template
    name: Registered in GSM Net
    device_class: connectivity
    entity_category: diagnostic 
    #trigger_on_initial_state: true
    id: senreg
#датчик двери ALARM
  - platform: template
    name: Door
    device_class: door
    id: dver_
#датчик движения ALARM
  - platform: template
    name: Motion
    device_class: motion
    id: dvij_
#датчик питания ALARM
  - platform: template
    device_class: power
    name: Power
    id: power_
    filters: 
      - invert
#датчик дыма ALARM
  - platform: template
    device_class: smoke
    name: Smoke
    id: dym_
#датчик работы котла ALARM
  - platform: template
    device_class: problem
    name: Heater problem
    id: kotel_

switch:
#разрешение сообщений наружу
  - platform: template
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    name: Allow SMS Outbound
    id: outsms_
#разрешение опроса проца
  - platform: template
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    name: Allow Interchange
    id: interch_
#управление режимом охраны
  - platform: template
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    name: ARM
    id: arm_
#дежурный нагрев
  - platform: template
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    name: Heating Standby 
    id: dejNagr_
#основной нагрев
  - platform: template
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    name: Heating Full
    id: nagrev_
#включатель оборудованиия котла
  - platform: template
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    name: Heater
    id: kotelonoff_
#включение сирены
  - platform: template
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    name: Siren
    id: sirena_
#включение режима автоматических СМС отчетов TTIME
  - platform: template
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    name: TTIME mode
    id: ttime_


